"""finalna baza

Revision ID: 86b3777c6d7c
Revises: fe9b340aceec
Create Date: 2019-05-07 10:48:56.052426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b3777c6d7c'
down_revision = 'fe9b340aceec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_address_city', table_name='address')
    op.drop_index('ix_address_postal_number', table_name='address')
    op.drop_index('ix_address_street_name', table_name='address')
    op.drop_index('ix_address_street_number', table_name='address')
    op.drop_table('address')
    op.add_column('user', sa.Column('address', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('city', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('country', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('postal_number', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('tel_number', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_address'), 'user', ['address'], unique=False)
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=False)
    op.create_index(op.f('ix_user_country'), 'user', ['country'], unique=False)
    op.create_index(op.f('ix_user_postal_number'), 'user', ['postal_number'], unique=False)
    op.create_index(op.f('ix_user_tel_number'), 'user', ['tel_number'], unique=False)
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'id_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('id_address', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'user', 'address', ['id_address'], ['id'])
    op.drop_index(op.f('ix_user_tel_number'), table_name='user')
    op.drop_index(op.f('ix_user_postal_number'), table_name='user')
    op.drop_index(op.f('ix_user_country'), table_name='user')
    op.drop_index(op.f('ix_user_city'), table_name='user')
    op.drop_index(op.f('ix_user_address'), table_name='user')
    op.drop_column('user', 'tel_number')
    op.drop_column('user', 'postal_number')
    op.drop_column('user', 'country')
    op.drop_column('user', 'city')
    op.drop_column('user', 'address')
    op.create_table('address',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('street_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('street_number', sa.INTEGER(), nullable=True),
    sa.Column('postal_number', sa.INTEGER(), nullable=True),
    sa.Column('city', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_address_street_number', 'address', ['street_number'], unique=False)
    op.create_index('ix_address_street_name', 'address', ['street_name'], unique=False)
    op.create_index('ix_address_postal_number', 'address', ['postal_number'], unique=False)
    op.create_index('ix_address_city', 'address', ['city'], unique=False)
    # ### end Alembic commands ###
