"""prve promjene

Revision ID: fe9b340aceec
Revises: 
Create Date: 2019-05-06 14:27:43.440005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe9b340aceec'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('address',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('street_name', sa.String(length=64), nullable=True),
    sa.Column('street_number', sa.Integer(), nullable=True),
    sa.Column('postal_number', sa.Integer(), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_address_city'), 'address', ['city'], unique=False)
    op.create_index(op.f('ix_address_postal_number'), 'address', ['postal_number'], unique=False)
    op.create_index(op.f('ix_address_street_name'), 'address', ['street_name'], unique=False)
    op.create_index(op.f('ix_address_street_number'), 'address', ['street_number'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('id_address', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_address'], ['address.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_surname'), 'user', ['surname'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('trip',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_name', sa.String(length=128), nullable=True),
    sa.Column('max_number', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('destination', sa.String(length=64), nullable=True),
    sa.Column('trip_description', sa.Text(length=1000), nullable=True),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_destination'), 'trip', ['destination'], unique=False)
    op.create_index(op.f('ix_trip_end_date'), 'trip', ['end_date'], unique=False)
    op.create_index(op.f('ix_trip_max_number'), 'trip', ['max_number'], unique=False)
    op.create_index(op.f('ix_trip_price'), 'trip', ['price'], unique=False)
    op.create_index(op.f('ix_trip_start_date'), 'trip', ['start_date'], unique=False)
    op.create_index(op.f('ix_trip_trip_description'), 'trip', ['trip_description'], unique=False)
    op.create_index(op.f('ix_trip_trip_name'), 'trip', ['trip_name'], unique=False)
    op.create_table('trip_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trip_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trip_user')
    op.drop_index(op.f('ix_trip_trip_name'), table_name='trip')
    op.drop_index(op.f('ix_trip_trip_description'), table_name='trip')
    op.drop_index(op.f('ix_trip_start_date'), table_name='trip')
    op.drop_index(op.f('ix_trip_price'), table_name='trip')
    op.drop_index(op.f('ix_trip_max_number'), table_name='trip')
    op.drop_index(op.f('ix_trip_end_date'), table_name='trip')
    op.drop_index(op.f('ix_trip_destination'), table_name='trip')
    op.drop_table('trip')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_surname'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_address_street_number'), table_name='address')
    op.drop_index(op.f('ix_address_street_name'), table_name='address')
    op.drop_index(op.f('ix_address_postal_number'), table_name='address')
    op.drop_index(op.f('ix_address_city'), table_name='address')
    op.drop_table('address')
    # ### end Alembic commands ###
